# Generated by Django 6.0.1 on 2026-01-28 18:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image')),
                ('category', models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('FASHION', 'Fashion'), ('HOME', 'Home'), ('ART', 'Art'), ('COLLECTIBLES', 'Collectibles'), ('VEHICLES', 'Vehicles'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=50, verbose_name='Category')),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('OPEN_BOX', 'Open Box'), ('USED_GOOD', 'Used - Good'), ('USED_FAIR', 'Used - Fair')], db_index=True, default='USED_GOOD', max_length=50, verbose_name='Condition')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuctionListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('FINISHED', 'Finished'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(db_index=True, verbose_name='End Time')),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Starting Price')),
                ('buy_now_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Buy Now Price')),
                ('current_price', models.DecimalField(db_index=True, decimal_places=2, max_digits=12, verbose_name='Current Price')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auctions', to=settings.AUTH_USER_MODEL, verbose_name='Winner')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='auctions.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BidTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auctionlisting')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-amount'],
                'indexes': [models.Index(fields=['auction', 'amount'], name='auctions_bi_auction_6f7787_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='check_bid_amount_positive')],
            },
        ),
        migrations.AddConstraint(
            model_name='auctionlisting',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='check_end_time_after_start_time'),
        ),
        migrations.AddConstraint(
            model_name='auctionlisting',
            constraint=models.CheckConstraint(condition=models.Q(('starting_price__gt', 0)), name='check_starting_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='auctionlisting',
            constraint=models.CheckConstraint(condition=models.Q(('current_price__gte', models.F('starting_price'))), name='check_current_price_gte_starting_price'),
        ),
    ]
