# Generated by Django 6.0.1 on 2026-01-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='current_price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12, verbose_name='Current Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('FASHION', 'Fashion'), ('HOME', 'Home'), ('ART', 'Art'), ('COLLECTIBLES', 'Collectibles'), ('VEHICLES', 'Vehicles'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('NEW', 'New'), ('OPEN_BOX', 'Open Box'), ('USED_GOOD', 'Used - Good'), ('USED_FAIR', 'Used - Fair')], db_index=True, default='USED_GOOD', max_length=50, verbose_name='Condition'),
        ),
    ]
