# Generated by Django 6.0 on 2026-01-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auctionlisting_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='end_time',
            field=models.DateTimeField(db_index=True, verbose_name='End Time'),
        ),
    ]
