# Generated by Django 6.0.1 on 2026-01-28 18:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Freely available money', max_digits=14, verbose_name='Balance')),
                ('held_balance', models.DecimalField(decimal_places=2, default=0, help_text='Money locked and awaiting payment (temporarily when you win the auction)', max_digits=14, verbose_name='Held Balance')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw'), ('BID_HOLD', 'Bid Hold'), ('BID_RELEASE', 'Bid Release'), ('PAYMENT', 'Payment'), ('REFUND', 'Refund')], db_index=True, max_length=20, verbose_name='Transaction Type')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reference_id', models.CharField(blank=True, db_index=True, help_text='e.g. Auction ID or Stripe Charge ID', max_length=100, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved - Paid'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('bank_details', models.TextField(help_text='IBAN, Swift, Account Number, etc.', verbose_name='Bank Details / Notes')),
                ('admin_note', models.TextField(blank=True, null=True, verbose_name='Admin Note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='check_wallet_balance_positive'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('held_balance__gte', 0)), name='check_held_balance_positive'),
        ),
    ]
