# Generated by Django 6.0.1 on 2026-01-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='reference_id',
            field=models.CharField(blank=True, db_index=True, help_text='e.g. Auction ID or Stripe Charge ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw'), ('BID_HOLD', 'Bid Hold'), ('BID_RELEASE', 'Bid Release'), ('PAYMENT', 'Payment'), ('REFUND', 'Refund')], db_index=True, max_length=20, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved - Paid'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20, verbose_name='Status'),
        ),
    ]
